services:
  go2rtc:
    image: alexxit/go2rtc:latest
    container_name: go2rtc
    ports:
      - "1984:1984"
      - "8554:8554"
      - "8555:8555"
    volumes:
      - ../config/go2rtc.yaml:/config/go2rtc.yaml:ro
    restart: unless-stopped

